
# Convert Excel data into Python List.
# This file is for dataset `Kampung Hutan Balas`.

import pandas as pd

path = r"/Users/yeetengm/Library/CloudStorage/OneDrive-UNIVERSITYUTARAMALAYSIA/yeetengm's mac/SEM 7/Final Year Project/Location Distance Matrix/Kampung Hutan Balas (Python list).xlsx"

df = pd.read_excel(path)

de = list(df.De)
trek = list(df.Trek)
dewan = list(df.Dewan)	
pida = list(df.Pida)
kara = list(df.Karakod)
al = list(df.Almilin)
ice = list(df.Ice)
surau = list(df.Surau)
tom = list(df.Tomyam)	
run = list(df.Runcit)
urut = list(df.Urut)
cik = list(df.Cik)
roti = list(df.Roti)
boba = list(df.Boba)
maksu = list(df.Maksu)
taman = list(df.Taman)
agro = list(df.Agrobazaar)
smk = list(df.SMK)
pappa = list(df.PappaNakaL)
tlc = list(df.TLC)
yr = list(df.YR)
aw = list(df.AW)
sz = list(df.SZ)
kepulu = list(df.Kepulu)
b = list(df.b)
hp = list(df.HP)
res = list(df.Restoren)

print(de)
print(trek)
print(dewan)	
print(pida)
print(kara)
print(al)	
print(ice)
print(surau)
print(tom)
print(run)
print(urut)
print(cik)
print(roti)
print(boba)
print(maksu)
print(taman)
print(agro)
print(smk)
print(pappa)
print(tlc)
print(yr)
print(aw)
print(sz)
print(kepulu)
print(b)
print(hp)
print(res)
